### ISSUE TITLE
Contribution related problem

### ISSUE THREAD

**Issue by AryamanGurjar** [dev-redakai/HubForHacktober_first_pull#1]
Hello, Sir I am Aryaman new to open source 
I have choose our repository to contribute .
I have contributed c program (Palindrome Program Using Stack).
and push mychanges even though git is is showing no changes
![git](https://user-images.githubusercontent.com/82881082/135662633-8b4776dc-9b5c-4716-91f0-65e94a3a5467.PNG)

can me suggest me what to do

I have added this
![git 2](https://user-images.githubusercontent.com/82881082/135662772-aa596b53-6bb7-458e-87c5-d7d9b3897695.PNG)

**Comment by dev-redakai** [comment]
Hi, please follow the instructions given on the home page of repo/readme.md
